# Generated by Django 3.2.19 on 2025-09-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
