# Generated by Django 3.2.19 on 2025-09-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtema', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tema.tema')),
            ],
            options={
                'verbose_name_plural': 'SubTema',
            },
        ),
    ]
