# Generated by Django 5.2.5 on 2025-09-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('morada', models.CharField(max_length=200)),
                ('tel', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
