# Generated by Django 5.2.5 on 2025-09-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_contactos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactos',
            new_name='Contacto',
        ),
    ]
