# Generated by Django 3.2.19 on 2025-09-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='func',
            name='tempo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
