# Generated by Django 5.2.5 on 2025-09-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_contactos_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tel',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
    ]
