# Generated by Django 5.2.5 on 2025-09-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_contacto_tel_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
